# Generated by Django 4.2.19 on 2025-02-17 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_options_alter_client_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_client_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Client Email')),
                ('appointment_time', models.TimeField(verbose_name='Appointment Time')),
                ('appointment_date', models.DateField(verbose_name='Appointment Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('appointment_status', models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=10, verbose_name='Appointment Status')),
                ('appointment_type', models.CharField(choices=[('introduction', 'Introduction'), ('single_session', 'Single Session'), ('month_plan', 'Month Plan'), ('annual_plan', 'Annual Plan')], max_length=20, verbose_name='Appointment Type')),
                ('appointment_notes', models.TextField(blank=True, help_text='Add any additional notes about the appointment', null=True, verbose_name='Appointment Notes')),
                ('appointment_url', models.URLField(blank=True, help_text='URL link to the appointment (if needed)', null=True, verbose_name='Appointment URL')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client', verbose_name='Client')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'indexes': [models.Index(fields=['appointment_client_email', 'appointment_date', 'appointment_time'], name='appointment_appoint_7d6049_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('appointment_client_email', 'appointment_date', 'appointment_time'), name='unique_appointment_per_client_time'),
        ),
    ]
