"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=fk=0)8sjiwmlf5j1$)-vv$)(inu57q)!w_p_f7!%7m%$6po52'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',  # Esta línea debe estar presente
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',  # Tu aplicación personalizada
    'rest_framework',  # Django REST Framework
    'corsheaders',  # Django CORS Headers
    'channels',  # Añadir Channels aquí

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Agregar CORS al inicio
    'django.contrib.sessions.middleware.SessionMiddleware',  # Debe ir primero
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Debe ir después de SessionMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',  # Debe ir después de AuthenticationMiddleware
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOW_ALL_ORIGINS = True  # Permitir todas las solicitudes (para desarrollo)


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'JesusApp',  # Cambia esto por el nombre de tu base de datos
        'USER': 'postgres',  # Cambia esto por tu usuario de PostgreSQL
        'PASSWORD': 'Ilargia1234',  # Cambia esto por tu contraseña
        'HOST': '127.0.0.1',  # O la dirección de tu servidor PostgreSQL
        'PORT': '5432',  # Puerto predeterminado para PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Throttling
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'throttling.CustomAnonRateThrottle',  # Sin espacios extra
        'rest_framework.throttling.UserRateThrottle',  # Limita a los usuarios autenticados
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',  # Limita a 5 solicitudes por minuto para usuarios anónimos
        'user': '100/minute',  # Limita a 10 solicitudes por minuto para usuarios autenticados
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Número de elementos por página
}


CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Agrega la URL de tu frontend (React)
]


# settings.py

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

X_FRAME_OPTIONS = 'DENY'  # Esto evitará que tu página se cargue dentro de un iframe en cualquier otro dominio

ASGI_APPLICATION = 'backend.asgi.application'

# settings.py

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],  # Asegúrate de que Redis esté corriendo en esta dirección
        },
    },
}




