# Generated by Django 4.2.17 on 2024-12-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artitle_title', models.CharField(max_length=100)),
                ('article_slug', models.SlugField(blank=True, unique=True)),
                ('article_day_posted', models.DateField()),
                ('article_first_paragraph', models.TextField()),
                ('article_second_paragraph', models.TextField(blank=True, null=True)),
                ('article_third_paragraph', models.TextField(blank=True, null=True)),
                ('article_fourth_paragraph', models.TextField(blank=True, null=True)),
                ('article_fifth_paragraph', models.TextField(blank=True, null=True)),
                ('article_images', models.JSONField(blank=True, default=list)),
                ('article_category', models.CharField(blank=True, max_length=100, null=True)),
                ('reading_time', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['article_slug'], name='blog_articl_article_8e1f21_idx')],
                'unique_together': {('artitle_title', 'article_slug')},
            },
        ),
    ]
