# Generated by Django 4.2.19 on 2025-02-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogsubscriber_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-article_day_posted']},
        ),
    ]
