# Generated by Django 4.2.17 on 2024-12-28 12:13

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40, verbose_name='Nombre del cliente')),
                ('client_surname', models.CharField(max_length=40, verbose_name='Apellido del cliente')),
                ('client_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('has_had_intro', models.BooleanField(default=False, verbose_name='¿Ha recibido introducción gratuita?')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['client_email'], name='client_email_idx')],
            },
        ),
    ]
